### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by mtl00p** [gentilkiwi/wanakiwi#1]
Tool throws ,"ERROR wmain ; Process not found..."  error. Please address.

**Comment by cybergibbons** [comment]
The code requires that the WannaCry process has specific names. 

https://github.com/gentilkiwi/wanakiwi/blob/master/main.c#L162

You can specify the PID of the process on the command line instead.

**Comment by gentilkiwi** [comment]
Wow, what a support :) Thank you to answer that for me (I'm sleeping a little bit ;))
I often see this when it's a filename renamed for forensic (hash, malware.exe, etc.) ; in this case, yes, you can use PID number as first argument on command line.
if it's another filename that I did not know, I will add it to the list with great pleasure.

**Comment by mtl00p** [comment]
Thanks a ton! @cybergibbons
