### ISSUE TITLE
Can not sent via gmail

### ISSUE THREAD

**Issue by rebelhn** [gentilkiwi/wanakiwi#14]
I downloaded wanakiwi-master.zip to my computer. Then I want to open it from another PC, so I attached this file and send via Gmail but it was blocked. What is the reason?

**Comment by rnbhat** [comment]
If Needed in another PC, mail this link and download there
https://github.com/gentilkiwi/wanakiwi/releases/download/0.1/wanakiwi.zip
Gmail Blocks exe attachments.

**Comment by war59312** [comment]
FYI: Even in zip files it can block it. To really send via gmail. Easy way is to encrypt it using 7zip.

**Comment by saxbophone** [comment]
You can also try renaming the file extension, or putting it in a ZIP nested in a ZIP nested in a ZIP. I'm not sure how many levels deep into ZIPs gmail scans, but the recommendation for IT departments seems to be 'scan at least two levels into ZIPs'. There's also WeTransfer

**Comment by dablackfox** [comment]
rename the .zip to .zap. This is recommended by gmail themselfs.

**Comment by saxbophone** [comment]
@dablackfox lol, really??? That's incredible, and hilarious! :laughing:

**Comment by Gdnedemon** [comment]
ya ya i see it says blocked for security reason's

**Comment by Gdnedemon** [comment]
As a security measure to prevent potential viruses, Gmail doesn't allow you to send or receive files with following extensions :

"ade", "adp", "bat", "chm", "cmd", "com", "cpl", "exe",
"hta", "ins", "isp", "jse", "lib", "mde", "msc", "msp",
"mst", "pif", "scr", "sct", "shb", "sys", "vb", "vbe",
"vbs", "vxd", "wsc", "wsf", "wsh"

**Comment by war59312** [comment]
@Gdnedemon List is outdated. ;)

Missing ".js" as in JavaScript files.

Here is the full official list: https://support.google.com/mail/answer/6590#messageswattachments
