### ISSUE TITLE
How to build .exe?

### ISSUE THREAD

**Issue by kkoomen** [gentilkiwi/wanakiwi#19]
Hi there, 

How should this be used? I saw that the [wannakey](https://github.com/aguinet/wannakey) repo has an `.exe` file. Is there a way to make a build into an `.exe`? I'd like to just have 1 single file. It's not that clear to me how to use and install this.

If someone could elaborate more on the usage, then thanks in advantage.

**Comment by Gdnedemon** [comment]
May i thought useing C program creating a program in c and converting .tcpp to .exe file.

**Comment by blubberdiblub** [comment]
Just click on the **Releases** tab where you can download .zip or .7z archives that already include the .exe

**Comment by kkoomen** [comment]
@blubberdiblub thanks!
