### ISSUE TITLE
wanakiwi is not work correctly

### ISSUE THREAD

**Issue by tUn4** [gentilkiwi/wanakiwi#2]
Hi,
i have tested the tool and if process name of ransomware is not "wnry.exe", wanakiwi is not work.

**Comment by gentilkiwi** [comment]
Please, see #1

**Comment by tUn4** [comment]
Thanks, i did not see any user guide to use the tool with PID argument. would you add some line to README file?
i guessed that is **wanakiwi.exe [PID_ID]** and it worked.
