### ISSUE TITLE
Can't downdload wannakiwi 9.2 and 0.2.7

### ISSUE THREAD

**Issue by Rheminecrafters** [gentilkiwi/wanakiwi#20]
I keep on seeing it say failed- network error. And do I need all of these files

**Comment by pogreb** [comment]
How download exe file ?

**Comment by tfksilent** [comment]
How download exe file ?

**Comment by gentilkiwi** [comment]
Be aware that some antivirus can prevent you to download wanakiwi or other files related to this ransomware.
