### ISSUE TITLE
 Can wanakiwi add a feature to decrypt the files using '00000000.dky'?

### ISSUE THREAD

**Issue by gregorytg** [gentilkiwi/wanakiwi#26]
Can wanakiwi add a feature to decrypt the files using '00000000.dky'?

We have paid the ransom amount of $300 and got a message from attackers like they have confirmed the payment(last week).
But when I click 'Decrypt' and 'start' button.
The '@WanaDecryptor@.exe' application crashed and showing 'Load PerfMon Counters has stopped working'. And, I was not able to decrypt the files.
![payment](https://user-images.githubusercontent.com/15854177/27084078-3754d4a8-5068-11e7-904d-e0fbb172b79d.png)
![error message](https://user-images.githubusercontent.com/15854177/27084084-394df136-5068-11e7-83ed-650a4f038aa0.png)
Another issue, at the time of infection of ransomware, in C drive there was around 20 GB free space.
But now, it shows automatically 'no free space'.So I thought because of this issue the decryption process has stopped. Then, I deleted some of the unwanted files from C drive and then again ran the application. But, still the application has crashed.
The '@WanaDecryptor@.exe' application, I have restored it from the list of quarantined files.

Also, at the time of confirmation of payment, there is a file created namely - '00000000.dky'(Key created or dropped by ransomware authors)

Operating System- Windows Server 2008 R2 Enterprise

**Comment by gentilkiwi** [comment]
Hello Gregory,

For sensitive operations, don't hesitate to contact me by mail ( benjamin [at] gentilkiwi.com )
Wanakiwi is able to use `00000000.dky` file if this one is in the same directory of the program (but you can specify path like: `wanakiwi.exe /priv:path\to\00000000.dky`)

Don't hesitate to send me `00000000.dky` file with one file you can decrypt, and another file you can't.
Another issue can be you had multiple encryption routines on same machine... search for multiple *.eky files on your disk

**Comment by gentilkiwi** [comment]
Files was encrypted with another instance of the ransomware.
