### ISSUE TITLE
Include OpenSSL acknowledgement notice

### ISSUE THREAD

**Issue by saxbophone** [gentilkiwi/wanakiwi#3]
If I understand it correctly, the OpenSSL license requires an acknowledgement notice when redistributed.

From section 6 of the OpenSSL License (https://github.com/openssl/openssl/blob/6faa345/LICENSE#L41-L44):

```
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.openssl.org/)"
```

**Comment by gentilkiwi** [comment]
You're totally right.
Usually I don't use OpenSSL lib and was not aware of this klind of Licence.

Be sure I'll update it tonight with other commit. I hope they will undersand I tried to go fast, especially at 4/5h in the morning.

**Comment by saxbophone** [comment]
No problem, these things are very easy to overlook and I'm sure they'll understand that you didn't mean any harm :)

**Comment by war59312** [comment]
Close? I see it on Readme page now.

**Comment by saxbophone** [comment]
Well spotted. Yes, time to close this methinks. Good stuff @gentilkiwi
