### ISSUE TITLE
How to decrypt if we have the decryption key

### ISSUE THREAD

**Issue by RoARene317** [gentilkiwi/wanakiwi#30]
How to do that and is this program compatible with windows 10??

**Comment by okyanusoz** [comment]
It is not compatiable as far as I know in Windows 10 in my tests. But, if you download winapi_check from WannaKey and run it, you can see the result for yourself.

**Comment by okyanusoz** [comment]
Winapi_check will test your system aganist this by creating a key and then trying to destroy the key.

**Comment by okyanusoz** [comment]
Also, if you have the key, see #26
