### ISSUE TITLE
Explain why the utility also works on non-XP?

### ISSUE THREAD

**Issue by Vdragon** [gentilkiwi/wanakiwi#4]
Hello @aguinet and @gentilkiwi , I wonder why the method also works with non-XP, mind update the README a bit if you have the info?

Thanks :+1:

**Comment by gentilkiwi** [comment]
I never sayed it does not works with non-XP...
@msuiche and I even made tests and provided screenshots for others versions.

**Comment by Vdragon** [comment]
I just notice that the original only say that it won't work on Win10
Anyway thanks!
