### ISSUE TITLE
wmain process not found

### ISSUE THREAD

**Issue by LarBob** [gentilkiwi/wanakiwi#8]
So I ran wannacry on a secluded computer to test this out, but it just says wmain process not found when run. I can see that the sample I used is running in the background as well as the wana decryptor 2.0 obviously. Does it not work with certain strands or something? I think it's just not detecting it.

**Comment by BT36** [comment]
same here windows 7

**Comment by gentilkiwi** [comment]
Take a look #1

**Comment by rnbhat** [comment]
By Renaming wnry.exe I Got error saying _Unfortunately No Correct key Private key in Memory_. The PID Appeared there was the PID of this file, not of Wannacry. By mentioning the PID of wcry problem Solved. I think mentioning PID of wcry wold be better.
![screen shot](https://cloud.githubusercontent.com/assets/28265454/26272452/ef08737a-3d35-11e7-8222-cf858b0a4e8b.jpg)
